/**
 * ComplyVault branded PDF generation using PDFKit.
 * Pure Node.js implementation for Vercel/serverless compatibility.
 */

import fs from "node:fs";
import path from "node:path";
import PDFDocument from "pdfkit";
import type { ExportPayload } from "./python-pdf";

const PAGE_W = 612;
const PAGE_H = 792;
const HEADER_H = 48;
const FOOTER_H = 32;
const LOGO_W = 34;
const LOGO_H = 34;
const LEFT = 36;
const RIGHT = 36;
const TOP = 62;
const BOTTOM = 44;
const USABLE = 540;

const COLORS = {
  DARK_GREEN: "#0D2818",
  MID_GREEN: "#1A4731",
  ACCENT_GREEN: "#2ECC71",
  LIGHT_GREEN: "#E8F5EE",
  GRAY: "#6B7280",
  DARK_TEXT: "#111827",
  RED_FLAG: "#DC2626",
  YELLOW_FLAG: "#D97706",
  ROW_RED: "#FEF2F2",
  ROW_YELLOW: "#FFFBEB",
  ROW_GREEN: "#F0FDF4",
  AMBER_BG: "#FFFBEB",
  AMBER_BORDER: "#F59E0B",
  AMBER_TEXT: "#92400E",
  BORDER: "#D1FAE5",
  NOTICE_BG: "#F9FAFB",
  WHITE: "#FFFFFF",
};

function formatTime(sec: number): string {
  const h = Math.floor(sec / 3600);
  const m = Math.floor((sec % 3600) / 60);
  const s = Math.floor(sec % 60);
  if (h > 0) return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
  return `${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
}

function truncate(text: string, maxLines: number): string {
  if (!text) return "";
  const lines = text.replace(/\r\n/g, "\n").split("\n").slice(0, maxLines);
  return lines.join("\n") + (lines.length >= maxLines ? "..." : "");
}

function severityToSpec(sev: string): string {
  const m: Record<string, string> = { CRITICAL: "HIGH", WARN: "MEDIUM", INFO: "INFO" };
  return m[sev?.toUpperCase() ?? ""] ?? "INFO";
}

export async function generateBrandedPDF(payload: ExportPayload): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "letter",
      margins: { top: TOP, bottom: BOTTOM, left: LEFT, right: RIGHT },
      bufferPages: true,
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    let pageNum = 0;
    const drawHeader = () => {
      pageNum++;
      doc.save();
      doc.rect(0, doc.page.height - HEADER_H, PAGE_W, HEADER_H).fill(COLORS.DARK_GREEN);
      doc.fillColor(COLORS.WHITE).fontSize(13).font("Helvetica-Bold").text("ComplyVault", 72, doc.page.height - 30);
      doc.fillColor(COLORS.ACCENT_GREEN).fontSize(7.5).font("Helvetica");
      doc.text(`${payload.firm_name}  ·  ${payload.date}`, PAGE_W - 200, doc.page.height - 36, { width: 164, align: "right" });
      doc.text("COMPLIANCE AUDIT PACK", PAGE_W - 200, doc.page.height - 22, { width: 164, align: "right" });
      const logoPath = path.join(process.cwd(), "public", "complyvault-logo.png");
      if (fs.existsSync(logoPath)) {
        try {
          doc.image(logoPath, 32, doc.page.height - HEADER_H + (HEADER_H - LOGO_H) / 2, { width: LOGO_W, height: LOGO_H });
        } catch {
          /* ignore */
        }
      }
      doc.restore();
    };

    const drawFooter = () => {
      doc.save();
      doc.rect(0, 0, PAGE_W, FOOTER_H).fill(COLORS.DARK_GREEN);
      doc.fillColor(COLORS.GRAY).fontSize(7).font("Helvetica");
      doc.text(`Page ${pageNum}  |  ${payload.firm_name}  |  ${payload.client_name}  |  ${payload.date}`, LEFT, 11);
      doc.text("Generated by ComplyVault  |  complyvault.co", PAGE_W - RIGHT - 220, 11, { width: 220, align: "right" });
      doc.restore();
    };

    const drawWatermark = () => {
      if (!payload.watermarked) return;
      doc.save();
      doc.translate(306, 396).rotate(35);
      doc.opacity(0.04).fillColor(COLORS.ACCENT_GREEN).fontSize(48).font("Helvetica-Bold");
      doc.text("COMPLYVAULT", 0, 50, { align: "center", width: 300 });
      doc.text("REDACTED SAMPLE", 0, -50, { align: "center", width: 300 });
      doc.opacity(1);
      doc.restore();
    };

    let y = TOP;
    drawHeader();
    drawFooter();
    drawWatermark();

    // Disclaimer
    doc.rect(LEFT, y, USABLE, 40).fillAndStroke(COLORS.AMBER_BG, COLORS.AMBER_BORDER);
    doc.fillColor(COLORS.AMBER_TEXT).fontSize(8).font("Helvetica-Bold");
    doc.text(
      "This compliance note is generated from an AI-assisted transcription. The advisor must review, edit if necessary, and sign off before this document is considered final.",
      LEFT + 10,
      y + 12,
      { width: USABLE - 20, align: "center" }
    );
    y += 54;

    // Title
    doc.fillColor(COLORS.DARK_GREEN).fontSize(20).font("Helvetica-Bold");
    doc.text(payload.meeting_type, LEFT, y);
    y += 26;
    doc.fillColor(COLORS.GRAY).fontSize(9.5).font("Helvetica");
    doc.text(`${payload.client_name}  ·  ${payload.date}  ·  ${payload.advisor_name}`, LEFT, y);
    y += 20;

    // Meeting details table
    const details = [
      ["CLIENT", payload.client_name, "ADVISOR", payload.advisor_name],
      ["FIRM", payload.firm_name, "MEETING DATE", payload.date],
      ["MEETING TYPE", payload.meeting_type, "DURATION", payload.duration],
      ["FORMAT", payload.format, "PACK GENERATED", (payload.generated_at ?? "").slice(0, 19)],
      ["REVIEW STATUS", payload.review_status, "PACK VERSION", String(payload.pack_version)],
    ];
    const rowH = 22;
    details.forEach((row, i) => {
      const bg = i % 2 === 1 ? COLORS.LIGHT_GREEN : COLORS.WHITE;
      doc.rect(LEFT, y, USABLE, rowH).fill(bg);
      doc.rect(LEFT, y, USABLE, rowH).stroke(COLORS.BORDER);
      doc.fillColor(COLORS.GRAY).fontSize(8).font("Helvetica-Bold");
      doc.text(row[0]!, LEFT + 8, y + 8, { width: 78 });
      doc.text(row[2]!, LEFT + 278, y + 8, { width: 78 });
      doc.fillColor(COLORS.DARK_TEXT).font("Helvetica");
      doc.text(row[1]!, LEFT + 88, y + 8, { width: 188 });
      doc.text(row[3]!, LEFT + 368, y + 8, { width: 168 });
      y += rowH;
    });
    y += 14;

    // Compliance Flags
    doc.fillColor(COLORS.DARK_GREEN).fontSize(11.5).font("Helvetica-Bold");
    doc.text("COMPLIANCE FLAGS", LEFT, y);
    y += 16;
    doc.moveTo(LEFT, y).lineTo(LEFT + USABLE, y).strokeColor(COLORS.ACCENT_GREEN).stroke();
    y += 12;

    if (payload.flags?.length) {
      doc.rect(LEFT, y, 52, 24).fill(COLORS.DARK_GREEN);
      doc.rect(LEFT + 52, y, 104, 24).fill(COLORS.DARK_GREEN);
      doc.rect(LEFT + 156, y, 300, 24).fill(COLORS.DARK_GREEN);
      doc.rect(LEFT + 456, y, 84, 24).fill(COLORS.DARK_GREEN);
      doc.fillColor(COLORS.WHITE).fontSize(7.5).font("Helvetica-Bold");
      doc.text("SEV.", LEFT + 7, y + 9);
      doc.text("FLAG", LEFT + 59, y + 9);
      doc.text("DETAIL", LEFT + 163, y + 9);
      doc.text("STATUS", LEFT + 463, y + 9);
      y += 24;
      payload.flags.forEach((f) => {
        const sev = (f.severity ?? "INFO").toUpperCase();
        const bg =
          sev === "CRITICAL" ? COLORS.ROW_RED : sev === "WARN" ? COLORS.ROW_YELLOW : COLORS.ROW_GREEN;
        const textColor = sev === "CRITICAL" ? COLORS.RED_FLAG : sev === "WARN" ? COLORS.YELLOW_FLAG : COLORS.ACCENT_GREEN;
        doc.rect(LEFT, y, USABLE, 24).fill(bg);
        doc.rect(LEFT, y, USABLE, 24).stroke(COLORS.BORDER);
        doc.fillColor(textColor).fontSize(7.5).font("Helvetica");
        doc.text(`● ${severityToSpec(f.severity)}`, LEFT + 7, y + 9);
        doc.text(String(f.type ?? "N/A"), LEFT + 59, y + 9, { width: 93 });
        doc.text(String((f.evidence as string) ?? "").slice(0, 80), LEFT + 163, y + 9, { width: 288 });
        doc.text(String(f.status ?? "N/A"), LEFT + 463, y + 9);
        y += 24;
      });
    } else {
      doc.fillColor(COLORS.GRAY).fontSize(8).text("No flags raised", LEFT, y);
      y += 16;
    }
    y += 14;

    // Action Items
    doc.fillColor(COLORS.DARK_GREEN).fontSize(11.5).font("Helvetica-Bold");
    doc.text("ACTION ITEMS", LEFT, y);
    y += 16;
    doc.moveTo(LEFT, y).lineTo(LEFT + USABLE, y).strokeColor(COLORS.ACCENT_GREEN).stroke();
    y += 12;

    if (payload.action_items?.length) {
      doc.rect(LEFT, y, 18, 20).fill(COLORS.DARK_GREEN);
      doc.rect(LEFT + 18, y, 259, 20).fill(COLORS.DARK_GREEN);
      doc.rect(LEFT + 277, y, 54, 20).fill(COLORS.DARK_GREEN);
      doc.rect(LEFT + 331, y, 54, 20).fill(COLORS.DARK_GREEN);
      doc.rect(LEFT + 385, y, 47, 20).fill(COLORS.DARK_GREEN);
      doc.fillColor(COLORS.WHITE).fontSize(7.5).font("Helvetica-Bold");
      doc.text("#", LEFT + 6, y + 7);
      doc.text("ACTION", LEFT + 24, y + 7);
      doc.text("OWNER", LEFT + 283, y + 7);
      doc.text("DUE", LEFT + 337, y + 7);
      doc.text("PRI.", LEFT + 391, y + 7);
      y += 20;
      payload.action_items.forEach((ai, i) => {
        const bg = i % 2 === 0 ? COLORS.LIGHT_GREEN : COLORS.WHITE;
        doc.rect(LEFT, y, USABLE, 20).fill(bg);
        doc.rect(LEFT, y, USABLE, 20).stroke(COLORS.BORDER);
        const pri = (ai.priority ?? "LOW").toUpperCase();
        const priColor = pri === "HIGH" ? COLORS.RED_FLAG : pri === "MEDIUM" || pri === "MED" ? COLORS.YELLOW_FLAG : COLORS.ACCENT_GREEN;
        doc.fillColor(COLORS.DARK_TEXT).fontSize(7.5).font("Helvetica");
        doc.text(String(i + 1), LEFT + 6, y + 7);
        const actionStr = (ai.action ?? "").slice(0, 90);
        doc.text(actionStr + (actionStr.length >= 90 ? "..." : ""), LEFT + 24, y + 7, { width: 250 });
        doc.text(ai.owner ?? "Advisor", LEFT + 283, y + 7, { width: 48 });
        doc.text((ai.due ?? "TBD").slice(0, 10), LEFT + 337, y + 7, { width: 48 });
        doc.fillColor(priColor).text(ai.priority ?? "LOW", LEFT + 391, y + 7);
        y += 20;
      });
    } else {
      doc.fillColor(COLORS.GRAY).fontSize(8).text("No action items", LEFT, y);
      y += 16;
    }

    // Page break before structured note
    doc.addPage();
    drawHeader();
    drawFooter();
    drawWatermark();
    y = TOP;

    // Sections: Topics, Recommendations, Disclosures
    const sections = [
      { title: "1. TOPICS DISCUSSED", key: "topics" as const, empty: "None documented." },
      { title: "2. RECOMMENDATIONS MADE", key: "recommendations" as const, empty: "NOT YET RECOMMENDED - No recommendation made." },
      { title: "3. DISCLOSURES PROVIDED", key: "disclosures" as const, empty: "NO RECOMMENDATION MADE - No disclosures documented." },
    ];
    for (const sec of sections) {
      doc.fillColor(COLORS.DARK_GREEN).fontSize(11.5).font("Helvetica-Bold");
      doc.text(sec.title, LEFT, y);
      y += 16;
      doc.moveTo(LEFT, y).lineTo(LEFT + USABLE, y).strokeColor(COLORS.ACCENT_GREEN).stroke();
      y += 12;
      const items = payload[sec.key] ?? [];
      if (!items.length) {
        doc.fillColor(COLORS.MID_GREEN).fontSize(10).font("Helvetica-Bold");
        doc.text(sec.empty.split(" - ")[0]!, LEFT, y);
        y += 14;
        doc.fillColor(COLORS.DARK_TEXT).fontSize(8.5).font("Helvetica");
        doc.text(sec.empty.split(" - ")[1] ?? sec.empty, LEFT, y, { width: USABLE });
        y += 20;
      } else {
        items.forEach((item: string | { text: string }) => {
          const text = typeof item === "string" ? item : (item.text ?? "");
          doc.fillColor(COLORS.MID_GREEN).fontSize(10).font("Helvetica-Bold");
          doc.text(text.slice(0, 120), LEFT, y, { width: USABLE });
          y += 14;
          doc.fillColor(COLORS.DARK_TEXT).fontSize(8.5).font("Helvetica");
          doc.text(text, LEFT, y, { width: USABLE });
          y += 13 * Math.max(1, Math.ceil(text.length / 65)) + 12;
        });
      }
      y += 10;
    }

    // Page break - Evidence Map
    doc.addPage();
    drawHeader();
    drawFooter();
    drawWatermark();
    y = TOP;

    doc.fillColor(COLORS.DARK_TEXT).fontSize(8.5).font("Helvetica");
    doc.text(
      "Each row links a compliance claim to its precise moment in the meeting transcript. This map is generated automatically by ComplyVault and is designed to satisfy examiner requests for source documentation during regulatory review.",
      LEFT,
      y,
      { width: USABLE }
    );
    y += 36;

    if (payload.evidence_links?.length) {
      doc.rect(LEFT, y, 32, 20).fill(COLORS.DARK_GREEN);
      doc.rect(LEFT + 32, y, 133, 20).fill(COLORS.DARK_GREEN);
      doc.rect(LEFT + 165, y, 32, 20).fill(COLORS.DARK_GREEN);
      doc.rect(LEFT + 197, y, 47, 20).fill(COLORS.DARK_GREEN);
      doc.rect(LEFT + 244, y, 216, 20).fill(COLORS.DARK_GREEN);
      doc.rect(LEFT + 460, y, 25, 20).fill(COLORS.DARK_GREEN);
      doc.fillColor(COLORS.WHITE).fontSize(7.5).font("Helvetica-Bold");
      doc.text("ID", LEFT + 5, y + 7);
      doc.text("CLAIM", LEFT + 37, y + 7);
      doc.text("TIME", LEFT + 170, y + 7);
      doc.text("SPEAKER", LEFT + 202, y + 7);
      doc.text("TRANSCRIPT SNIPPET", LEFT + 249, y + 7);
      doc.text("CONF", LEFT + 465, y + 7);
      y += 20;
      payload.evidence_links.forEach((ev, i) => {
        const bg = i % 2 === 0 ? COLORS.LIGHT_GREEN : COLORS.WHITE;
        doc.rect(LEFT, y, USABLE, 24).fill(bg);
        doc.rect(LEFT, y, USABLE, 24).stroke(COLORS.BORDER);
        doc.fillColor(COLORS.ACCENT_GREEN).fontSize(7.5).font("Helvetica-Bold");
        doc.text(ev.id ?? `E${i + 1}`, LEFT + 5, y + 9);
        doc.fillColor(COLORS.DARK_TEXT).font("Helvetica");
        doc.text((ev.claim ?? "").slice(0, 80), LEFT + 37, y + 9, { width: 125 });
        doc.fillColor(COLORS.MID_GREEN).font("Helvetica-Bold");
        doc.text(formatTime(ev.startTime ?? 0), LEFT + 170, y + 9);
        doc.fillColor(COLORS.DARK_TEXT).font("Helvetica");
        doc.text(ev.speaker ?? "Unknown", LEFT + 202, y + 9, { width: 40 });
        doc.fillColor(COLORS.GRAY).font("Helvetica-Oblique");
        doc.text(truncate(ev.snippet ?? "", 3), LEFT + 249, y + 9, { width: 205 });
        doc.fillColor(COLORS.ACCENT_GREEN).font("Helvetica-Bold");
        doc.text(ev.confidence != null ? `${Math.round(ev.confidence * 100)}%` : "", LEFT + 465, y + 9);
        y += 24;
      });
    } else {
      doc.fillColor(COLORS.GRAY).fontSize(8).text("No evidence links.", LEFT, y);
    }

    // Page break - Sign-off & Audit Trail
    doc.addPage();
    drawHeader();
    drawFooter();
    drawWatermark();
    y = TOP;

    doc.fillColor(COLORS.DARK_GREEN).fontSize(11.5).font("Helvetica-Bold");
    doc.text("ADVISOR CERTIFICATION", LEFT, y);
    y += 16;
    doc.moveTo(LEFT, y).lineTo(LEFT + USABLE, y).strokeColor(COLORS.ACCENT_GREEN).stroke();
    y += 12;
    doc.fillColor(COLORS.DARK_TEXT).fontSize(8.5).font("Helvetica");
    doc.text(
      "I certify that this compliance note accurately reflects the topics discussed, recommendations made, disclosures provided, and action items agreed during the client meeting referenced above. This document has been reviewed for completeness and accuracy prior to finalization.",
      LEFT,
      y,
      { width: USABLE }
    );
    y += 48;

    const signoff = [
      ["ADVISOR NAME", payload.advisor_name, "DATE REVIEWED", payload.date_reviewed ?? ""],
      ["FIRM", payload.firm_name, "DATE SIGNED", payload.date_signed ?? ""],
      ["CRD NUMBER", "", "PACK VERSION", String(payload.pack_version)],
      ["SIGNATURE", "", "", ""],
    ];
    signoff.forEach((row, i) => {
      const bg = i % 2 === 0 ? COLORS.LIGHT_GREEN : COLORS.WHITE;
      doc.rect(LEFT, y, USABLE, 22).fill(bg);
      doc.rect(LEFT, y, USABLE, 22).stroke(COLORS.BORDER);
      doc.fillColor(COLORS.GRAY).fontSize(8).font("Helvetica-Bold");
      doc.text(row[0]!, LEFT + 8, y + 8);
      doc.text(row[2]!, LEFT + 278, y + 8);
      doc.fillColor(COLORS.DARK_TEXT).font("Helvetica");
      doc.text(row[1]!, LEFT + 88, y + 8);
      doc.text(row[3]!, LEFT + 368, y + 8);
      y += 22;
    });
    y += 14;

    doc.fillColor(COLORS.DARK_GREEN).fontSize(11.5).font("Helvetica-Bold");
    doc.text("SYSTEM AUDIT TRAIL", LEFT, y);
    y += 16;
    doc.moveTo(LEFT, y).lineTo(LEFT + USABLE, y).strokeColor(COLORS.ACCENT_GREEN).stroke();
    y += 12;

    if (payload.audit_trail?.length) {
      payload.audit_trail.forEach((row, i) => {
        const bg = i % 2 === 0 ? COLORS.LIGHT_GREEN : COLORS.WHITE;
        doc.rect(LEFT, y, USABLE, 20).fill(bg);
        doc.rect(LEFT, y, USABLE, 20).stroke(COLORS.BORDER);
        doc.fillColor(COLORS.DARK_TEXT).fontSize(7.5).font("Helvetica");
        doc.text(row.timestamp ?? "", LEFT + 5, y + 7, { width: 103 });
        doc.text(row.event ?? "", LEFT + 113, y + 7, { width: 125 });
        doc.text(row.user ?? "", LEFT + 243, y + 7, { width: 68 });
        doc.text(row.detail ?? "", LEFT + 316, y + 7, { width: 218 });
        y += 20;
      });
    }
    y += 14;

    doc.rect(LEFT, y, USABLE, 50).fill(COLORS.NOTICE_BG).stroke(COLORS.BORDER);
    doc.fillColor("#374151").fontSize(7.5).font("Helvetica");
    doc.text(
      "This compliance note has been generated by ComplyVault AI from a meeting recording. All content must be reviewed and approved by the advisor of record before use. complyvault.co",
      LEFT + 10,
      y + 10,
      { width: USABLE - 20 }
    );

    doc.end();
  });
}
